name: Get Latest Instructors # test change
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"
jobs:
  run:
    name: Get & Commit
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          repository: DennisTsar/RU-SIRS
          submodules: recursive
          token: ${{ secrets.PAT }}

      # Set up Java environment for the next steps
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Build & run application - update instructors file
      - name: Run
        run: ./gradlew local:run --args="-instructor"
        
      # Update repo with generated file
      - name: Add & Commit to Rutgers-SIRS
        id: git
        run: |
          cd local
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout master
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Updated latest instructors"
            git push
          else
            echo "CHANGE=false" >> $GITHUB_OUTPUT
          fi
      - name: Add & Commit to RU-SIRS
        if: steps.git.outputs.CHANGE != 'false'
        run: |
          git add local
          git commit -m "Updated latest instructors"
          git push
