name: Get Latest Instructors
on: [workflow_dispatch]
jobs:
  run:
    name: Get Latest Instructors
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Set up Java environment for the next steps
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Validate wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # Build application
      - name: Run
        run: ./gradlew run --args="-instructor"
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Uptated latest instructors'
#           add: '*.json --force'
